"""Post-process spec chunks fetched from portainer-api-docs.

Two jobs, run after `make specs` downloads the per-tag chunk files:

1. Shrink the boilerplate the upstream chunker repeats in every file:
   the `info.description` preamble (auth/security prose an agent never
   needs mid-lookup) becomes a one-line stub, and the all-tags `tags:`
   block is filtered down to the tags the chunk's own operations use
   (and the Redoc-only `x-tagGroups:` block is dropped).
   Both are textual edits, so the rest of the file keeps its upstream
   formatting. Idempotent. `openapi.yaml` (the root document) keeps
   its full tag list.
2. Generate INDEX.md — one line per operation
   (`METHOD /path → chunk file — summary`) so a single grep resolves
   any endpoint to the file that documents it.

Every chunk is parsed after stripping; a parse failure aborts with a
non-zero exit so a broken fetch can't be committed silently.

Run via: uv run --with pyyaml scripts/postprocess_specs.py references/spec --version 2.42.0
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

METHODS = ("get", "put", "post", "delete", "options", "head", "patch", "trace")
STUB = "  description: Portainer API (preamble stripped — see SKILL.md)\n"


def strip_preamble(text: str) -> str:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    i, in_info = 0, False
    while i < len(lines):
        line = lines[i]
        if line.rstrip("\n") == "info:":
            in_info = True
        elif in_info and re.match(r"^\S", line):
            in_info = False
        if in_info and re.match(r"^  description:", line):
            out.append(STUB)
            i += 1
            while i < len(lines) and not re.match(r"^\S|^  \S", lines[i]):
                i += 1
            continue
        out.append(line)
        i += 1
    return "".join(out)


def used_tags(spec: dict) -> set[str]:
    tags: set[str] = set()
    for item in (spec.get("paths") or {}).values():
        if not isinstance(item, dict):
            continue
        for method in METHODS:
            op = item.get(method)
            if isinstance(op, dict):
                tags.update(op.get("tags") or ())
    return tags


def drop_block(text: str, key: str) -> str:
    lines = text.splitlines(keepends=True)
    try:
        start = next(i for i, l in enumerate(lines) if l.rstrip("\n") == key)
    except StopIteration:
        return text
    end = next(
        (i for i in range(start + 1, len(lines)) if re.match(r"^\S", lines[i])),
        len(lines),
    )
    return "".join(lines[:start] + lines[end:])


def filter_tags(text: str, keep: set[str]) -> str:
    lines = text.splitlines(keepends=True)
    try:
        start = next(i for i, l in enumerate(lines) if l.rstrip("\n") == "tags:")
    except StopIteration:
        return text
    end = next(
        (i for i in range(start + 1, len(lines)) if re.match(r"^\S", lines[i])),
        len(lines),
    )

    items: list[list[str]] = []
    for line in lines[start + 1 : end]:
        if line.startswith("  - "):
            items.append([line])
        else:
            items[-1].append(line)
    kept = [
        item
        for item in items
        if yaml.safe_load("".join(item))[0].get("name") in keep
    ]
    block = ["tags:\n"] + [l for item in kept for l in item] if kept else []
    return "".join(lines[:start] + block + lines[end:])


def build_index(specs: dict[str, dict], version: str) -> str:
    ops: dict[tuple[str, str], dict] = {}
    for name, spec in sorted(specs.items()):
        if name == "openapi.yaml":  # root document, $refs into the chunks
            continue
        for path, item in (spec.get("paths") or {}).items():
            if not isinstance(item, dict):
                continue
            for method in METHODS:
                op = item.get(method)
                if not isinstance(op, dict):
                    continue
                summary = " ".join(
                    str(op.get("summary") or op.get("operationId") or "").split()
                )
                entry = ops.setdefault(
                    (path, method), {"files": [], "summary": summary}
                )
                if name not in entry["files"]:
                    entry["files"].append(name)

    lines = [
        f"# Portainer EE {version} operation index"
        " — generated by `make specs`; do not edit.",
        "# Format: METHOD /path → chunk file — summary",
    ]
    for path, method in sorted(ops, key=lambda k: (k[0], METHODS.index(k[1]))):
        entry = ops[(path, method)]
        line = f"{method.upper()} {path} → {', '.join(entry['files'])}"
        if entry["summary"]:
            line += f" — {entry['summary']}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec_dir", type=Path)
    parser.add_argument("--version", required=True)
    args = parser.parse_args(argv)

    files = sorted(args.spec_dir.glob("*.yaml"))
    if len(files) < 2:
        print(f"error: no chunk set in {args.spec_dir}", file=sys.stderr)
        return 1

    specs: dict[str, dict] = {}
    for f in files:
        stripped = strip_preamble(f.read_text())
        try:
            spec = yaml.safe_load(stripped)
            if f.name != "openapi.yaml":
                stripped = filter_tags(stripped, used_tags(spec))
                stripped = drop_block(stripped, "x-tagGroups:")
                spec = yaml.safe_load(stripped)
        except yaml.YAMLError as exc:
            print(f"error: {f.name} no longer parses: {exc}", file=sys.stderr)
            return 1
        specs[f.name] = spec
        f.write_text(stripped)

    index = build_index(specs, args.version)
    (args.spec_dir / "INDEX.md").write_text(index)
    n_ops = sum(1 for line in index.splitlines() if not line.startswith("#"))
    print(
        f"{len(files)} chunks stripped and validated, {n_ops} operations indexed",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
